import { NextRequest, NextResponse } from 'next/server'
import { Resend } from 'resend'

export async function POST(request: NextRequest) {
  try {
    const { email } = await request.json()

    if (!email || !email.includes('@')) {
      return NextResponse.json(
        { success: false, error: 'Valid email is required' },
        { status: 400 }
      )
    }

    if (!process.env.RESEND_API_KEY) {
      console.error('RESEND_API_KEY is not configured')
      return NextResponse.json(
        { success: false, error: 'Email service not configured' },
        { status: 500 }
      )
    }

    const resend = new Resend(process.env.RESEND_API_KEY)

    // Send email notification using Resend
    try {
      const emailResult = await resend.emails.send({
        from: 'StyleGen <noreply@resend.dev>', // You can customize this domain later
        to: 'sardornodirov.25@gmail.com',
        subject: '🎨 New StyleGen Waitlist Signup!',
        html: `
          <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
            <h2 style="color: #7c3aed; margin-bottom: 20px;">
              🎨 New StyleGen Waitlist Signup!
            </h2>
            
            <div style="background-color: #f8fafc; padding: 20px; border-radius: 8px; margin: 20px 0;">
              <h3 style="margin: 0 0 15px 0; color: #1e293b;">User Details:</h3>
              <p style="margin: 5px 0;"><strong>Email:</strong> ${email}</p>
              <p style="margin: 5px 0;"><strong>Timestamp:</strong> ${new Date().toLocaleString()}</p>
              <p style="margin: 5px 0;"><strong>Source:</strong> StyleGen Landing Page</p>
            </div>

            <div style="background-color: #eff6ff; padding: 15px; border-radius: 6px; border-left: 4px solid #3b82f6;">
              <p style="margin: 0; color: #1e40af;">
                💡 <strong>Next Steps:</strong> Consider following up with this user about early access or product updates!
              </p>
            </div>

            <hr style="margin: 30px 0; border: none; border-top: 1px solid #e2e8f0;">
            
            <p style="font-size: 14px; color: #64748b; margin: 0;">
              This email was automatically generated by your StyleGen waitlist system.
            </p>
          </div>
        `,
        text: `
New StyleGen Waitlist Signup!

User Details:
- Email: ${email}
- Timestamp: ${new Date().toLocaleString()}
- Source: StyleGen Landing Page

Next Steps: Consider following up with this user about early access or product updates!

---
This email was automatically generated by your StyleGen waitlist system.
        `
      })

      console.log('Email sent successfully:', emailResult)

      return NextResponse.json({ 
        success: true, 
        message: 'Successfully joined waitlist!' 
      })

    } catch (emailError) {
      console.error('Failed to send email:', emailError)
      
      // Still return success to user, but log the email failure
      // This way the user experience isn't broken if email fails
      return NextResponse.json({ 
        success: true, 
        message: 'Successfully joined waitlist!' 
      })
    }

  } catch (error) {
    console.error('Waitlist signup error:', error)
    return NextResponse.json(
      { success: false, error: 'Internal server error' },
      { status: 500 }
    )
  }
} 